listener 8883
protocol mqtt

cafile /home/f3c4b4/Documentos/TFG/mqtt_tls/certs/ca.crt
certfile /home/f3c4b4/Documentos/TFG/mqtt_tls/certs/server.crt
keyfile /home/f3c4b4/Documentos/TFG/mqtt_tls/certs/server.key

require_certificate true
use_identity_as_username true

allow_anonymous false
persistence true
persistence_location /tmp/mosquitto/
log_type all
